
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package servidor;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-11-21T10:59:37.371-03:00
 * Generated source version: 3.4.5
 *
 */
public class servidorAplicacao_PortTypeClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://servidor/", "servidorAplicacaoService");
        QName portName = new QName("http://servidor/", "servidorAplicacaoPort");

        Service service = Service.create(serviceName);
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
                        "http://localhost:9090/servidorAplicacaoPort");
        servidor.servidorAplicacao_PortType client = service.getPort(portName,  servidor.servidorAplicacao_PortType.class);

        // Insert code to invoke methods on the client here
    }

}