
package servidor;

import javax.jws.WebParam.Mode;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-11-21T10:59:37.356-03:00
 * Generated source version: 3.4.5
 *
 */

@WebService
public interface servidorAplicacao_PortType {

    public float somar(

        float arg0,
        float arg1
    );

    public float dividir(

        float arg0,
        float arg1
    );

    public float subtrai(

        float arg0,
        float arg1
    );

    public float multiplicar(

        float arg0,
        float arg1
    );
}
