
package servidor;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-11-21T10:59:37.369-03:00
 * Generated source version: 3.4.5
 *
 */

public class servidorAplicacao_PortTypeServer{

    protected servidorAplicacao_PortTypeServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new servidor.servidorAplicacao();
        String address = "http://localhost:9090/servidorAplicacaoPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new servidorAplicacao_PortTypeServer();
        System.out.println("Server ready...");
        
        Thread.sleep(5 * 60 * 10000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}

